# Generated by Django 5.2.8 on 2025-12-01 16:37

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(db_column='notificationID', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=256)),
                ('notification_type', models.CharField(choices=[('DOCUMENT_REQUEST', 'Document Request'), ('LOAN_APPROVAL', 'Loan Approval'), ('INSTALLMENT_DUE', 'Installment Due'), ('PAYMENT_CONFIRMATION', 'Payment Confirmation'), ('SYSTEM', 'System Notification')], db_column='type', max_length=50)),
                ('link', models.CharField(blank=True, db_column='link', max_length=500, null=True)),
                ('subject', models.CharField(default='', max_length=255)),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('from_user', models.ForeignKey(db_column='fromID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to='users.user')),
                ('to_user', models.ForeignKey(db_column='toID', on_delete=django.db.models.deletion.CASCADE, related_name='received_notifications', to='users.user')),
            ],
            options={
                'db_table': 'notification',
                'ordering': ['-created_at'],
            },
        ),
    ]
