# Generated by Django 5.2.8 on 2025-12-01 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='link',
            field=models.CharField(db_column='link', default='', max_length=500),
        ),
    ]
