# Generated by Django 5.2.8 on 2025-12-01 16:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationHeader',
            fields=[
                ('id', models.UUIDField(db_column='simID', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('duration', models.IntegerField()),
                ('interest_rate', models.DecimalField(db_column='interestRate', decimal_places=2, max_digits=5)),
                ('simulation_date', models.DateTimeField(auto_now_add=True)),
                ('monthly_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('total_interest', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('total_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('user', models.ForeignKey(db_column='userID', on_delete=django.db.models.deletion.CASCADE, related_name='simulations', to='users.user')),
            ],
            options={
                'db_table': 'simulation_header',
                'ordering': ['-simulation_date'],
            },
        ),
        migrations.CreateModel(
            name='SimulationDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('installment_number', models.IntegerField(db_column='installmentID')),
                ('beginning_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('installment', models.DecimalField(decimal_places=2, max_digits=15)),
                ('interest_payment', models.DecimalField(decimal_places=2, max_digits=15)),
                ('principal_payment', models.DecimalField(decimal_places=2, max_digits=15)),
                ('ending_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('custom_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('is_prepayment', models.BooleanField(default=False)),
                ('is_delayed', models.BooleanField(default=False)),
                ('simulation', models.ForeignKey(db_column='simID', on_delete=django.db.models.deletion.CASCADE, related_name='details', to='simulations.simulationheader')),
            ],
            options={
                'db_table': 'simulation_detail',
                'ordering': ['simulation', 'installment_number'],
                'unique_together': {('simulation', 'installment_number')},
            },
        ),
    ]
