# Generated by Django 5.2.8 on 2025-12-01 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='verification_link',
            field=models.CharField(db_column='verificationLink', default='', max_length=255),
        ),
    ]
