# Generated by Django 5.2.8 on 2025-12-01 16:37

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.UUIDField(db_column='loanApplicationID', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_approved', models.BooleanField(db_column='isApproved', default=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('duration', models.IntegerField()),
                ('interest_rate', models.DecimalField(db_column='interestRate', decimal_places=2, max_digits=5)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'loan_application',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoanApplicationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'loan_application_document',
            },
        ),
        migrations.CreateModel(
            name='UserLoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'user_loan_application',
            },
        ),
        migrations.CreateModel(
            name='CustomerLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(db_column='customerID', on_delete=django.db.models.deletion.CASCADE, to='users.customer')),
            ],
            options={
                'db_table': 'customer_loan',
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.UUIDField(db_column='loanID', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('duration', models.IntegerField()),
                ('interest_rate', models.DecimalField(db_column='interestRate', decimal_places=2, max_digits=5)),
                ('payment', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAID_OFF', 'Paid Off'), ('DELINQUENT', 'Delinquent'), ('DEFAULTED', 'Defaulted')], default='ACTIVE', max_length=20)),
                ('disbursement_date', models.DateTimeField(db_column='disbursementDate')),
                ('commencing_date', models.DateTimeField(db_column='commencingDate')),
                ('customers', models.ManyToManyField(through='loans.CustomerLoan', to='users.customer')),
                ('staff', models.ForeignKey(db_column='staffID', on_delete=django.db.models.deletion.PROTECT, related_name='approved_loans', to='users.staff')),
            ],
            options={
                'db_table': 'loan',
                'ordering': ['-disbursement_date'],
            },
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('installment_number', models.IntegerField(db_column='installmentID')),
                ('due_amount', models.DecimalField(db_column='amount', decimal_places=2, max_digits=15)),
                ('due_date', models.DateTimeField(db_column='dueDate')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('PARTIAL', 'Partially Paid')], default='PENDING', max_length=20)),
                ('payment_amount', models.DecimalField(db_column='paymentAmount', decimal_places=2, default=0, max_digits=15)),
                ('payment_date', models.DateTimeField(blank=True, db_column='paymentDate', null=True)),
                ('principal_due', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('interest_due', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('late_fee', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('loan', models.ForeignKey(db_column='loanID', on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='loans.loan')),
            ],
            options={
                'db_table': 'installment',
                'ordering': ['loan', 'due_date'],
            },
        ),
        migrations.AddField(
            model_name='customerloan',
            name='loan',
            field=models.ForeignKey(db_column='loanID', on_delete=django.db.models.deletion.CASCADE, to='loans.loan'),
        ),
    ]
