# Generated by Django 5.2.8 on 2025-12-01 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('loans', '0001_initial'),
        ('simulations', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='simulation',
            field=models.ForeignKey(blank=True, db_column='simID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_applications', to='simulations.simulationheader'),
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_application',
            field=models.OneToOneField(db_column='loanApplicationID', on_delete=django.db.models.deletion.PROTECT, related_name='loan', to='loans.loanapplication'),
        ),
        migrations.AddField(
            model_name='loanapplicationdocument',
            name='document',
            field=models.ForeignKey(db_column='documentID', on_delete=django.db.models.deletion.CASCADE, to='documents.document'),
        ),
        migrations.AddField(
            model_name='loanapplicationdocument',
            name='loan_application',
            field=models.ForeignKey(db_column='loanApplicationID', on_delete=django.db.models.deletion.CASCADE, to='loans.loanapplication'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='documents',
            field=models.ManyToManyField(through='loans.LoanApplicationDocument', to='documents.document'),
        ),
        migrations.AddField(
            model_name='userloanapplication',
            name='loan_application',
            field=models.ForeignKey(db_column='loanApplicationID', on_delete=django.db.models.deletion.CASCADE, to='loans.loanapplication'),
        ),
        migrations.AddField(
            model_name='userloanapplication',
            name='user',
            field=models.ForeignKey(db_column='userID', on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='users',
            field=models.ManyToManyField(through='loans.UserLoanApplication', to='users.user'),
        ),
        migrations.AlterUniqueTogether(
            name='customerloan',
            unique_together={('customer', 'loan')},
        ),
        migrations.AlterUniqueTogether(
            name='loanapplicationdocument',
            unique_together={('loan_application', 'document')},
        ),
        migrations.AlterUniqueTogether(
            name='userloanapplication',
            unique_together={('user', 'loan_application')},
        ),
    ]
