# Generated by Django 5.2.8 on 2025-12-03 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_customerloan_created_at_installment_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installment',
            name='interest_due',
        ),
        migrations.RemoveField(
            model_name='installment',
            name='principal_due',
        ),
    ]
