# Generated by Django 5.2.8 on 2025-12-01 16:37

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(db_column='documentID', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=32)),
                ('document_type', models.CharField(choices=[('GOVT_ID', 'Government Photo ID'), ('PAYROLL', 'Pay Slip'), ('CREDIT_HISTORY', 'Credit History'), ('ADDRESS_PROOF', 'Proof of Address'), ('OTHER', 'Other')], db_column='type', max_length=50)),
                ('link', models.CharField(db_column='link', max_length=500)),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('file_size', models.IntegerField(default=0)),
                ('mime_type', models.CharField(default='application/octet-stream', max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_by', models.ForeignKey(blank=True, db_column='requestedBy', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_documents', to='users.staff')),
                ('uploaded_by', models.ForeignKey(db_column='uploadedBy', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to='users.user')),
            ],
            options={
                'db_table': 'document',
            },
        ),
    ]
