# Generated by Django 5.2.8 on 2025-12-02 16:06

import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='display_filename',
            field=models.CharField(db_column='displayFilename', default='', max_length=255),
        ),
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.FileField(db_column='file', default='', max_length=500, upload_to=documents.models.user_document_path),
        ),
        migrations.AddField(
            model_name='document',
            name='original_filename',
            field=models.CharField(db_column='originalFilename', default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='document',
            name='file_name',
            field=models.CharField(db_column='fileName', max_length=255),
        ),
        migrations.AlterField(
            model_name='document',
            name='file_path',
            field=models.CharField(db_column='filePath', default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='document',
            name='file_size',
            field=models.IntegerField(db_column='fileSize', default=0),
        ),
        migrations.AlterField(
            model_name='document',
            name='link',
            field=models.CharField(db_column='link', default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='document',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='updatedAt'),
        ),
        migrations.AlterField(
            model_name='document',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, db_column='uploadedAt'),
        ),
    ]
