# Generated by Django 5.2.8 on 2025-12-03 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_display_filename_document_file_and_more'),
        ('loans', '0004_remove_installment_interest_due_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='display_filename',
        ),
        migrations.RemoveField(
            model_name='document',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='document',
            name='file_path',
        ),
        migrations.AddField(
            model_name='document',
            name='loan_application',
            field=models.ForeignKey(blank=True, db_column='loanApplicationID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_documents', to='loans.loanapplication'),
        ),
        migrations.AddField(
            model_name='document',
            name='rejection_note',
            field=models.TextField(blank=True, db_column='rejectionNote', default=''),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('GOVT_ID', 'Government Photo ID'), ('PAYROLL', 'Pay Slip'), ('CREDIT_HISTORY', 'Credit History')], db_column='type', max_length=50),
        ),
    ]
