# Generated by Django 5.2.8 on 2025-12-03 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_remove_document_display_filename_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('GOVT_ID', 'Government Photo ID'), ('PAYROLL', 'Pay Slip'), ('CREDIT_HISTORY', 'Credit History'), ('BANK_STATEMENT', 'Bank Statement'), ('OTHER', 'Other')], db_column='type', max_length=50),
        ),
    ]
